name = "SHC Minecraft Server"
author = "ryleu"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2323a33247b95c2897cee530eb83acb496f6f2c57cc7fb8f6b25274f27f0f91a"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
