name = "SHC Minecraft Server"
author = "ryleu"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e313aee8313833765b7a0809a3f9618176f99e7d3238e28d719b10afee27bf3b"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
